[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "open-yt"
version = "0.1.1.6"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mutagen>=1.47.0",
    "pydantic-settings>=2.14.1",
    "pyfiglet>=1.0.4",
    "questionary>=2.1.1",
    "rich>=15.0.0",
    "tomli-w>=1.2.0",
    "typer>=0.25.1",
    "yt-dlp>=2026.3.17",
]

[project.scripts]
open-yt = "open_yt.main:app"

[tool.hatch.build.targets.wheel]
packages = ["src/open_yt"]